- charts/backend-service/Chart.yaml
- charts/backend-service/README.md
- charts/backend-service/templates/_envs.tpl
- charts/backend-service/templates/_truststore_envs.tpl
We used `--set hocs-backend-service.namespace=cs-dev` locally as an
argument to `helm template` to set the namespace in Helm, but this
isn't the right way to do it.
By changing it to use the Release built-in object instead of the values
user-defined one, we can use the -n argument to `helm template` which is
more robust.
> 🐛 HOCS-5561: Rename values.namespace to Release.Namespace

- charts/hocs-audit/Chart.yaml
- charts/hocs-audit/values.yaml
To enable simpler toggling of consuming from the queue, this change adds the `consumer` profile to the hocs-audit chart.
> Add consumer profile to audit

- charts/generic-service/Chart.yaml
- charts/generic-service/templates/_helpers.tpl
- charts/generic-service/templates/deployment.yaml
We want to deploy to prod using a 'clean' deployment but the environment variables env file is currently locked to the deployment name. This change allows us to pass a nameOverride of 'decs-casework' and a reference to deployment envs of 'hocs-casework'
> ✨ HOCS-5561: Allow Deployment name to be different to the chart name.

- charts/hocs-notify/Chart.yaml
- charts/hocs-notify/values.yaml
Notify doesn't require a service as it doesn't have any rest endpoints
> 🐛 HOCS-5561: Disable service from Notify

- charts/hocs-search-consumer/Chart.yaml
- charts/hocs-search-consumer/values.yaml
- charts/hocs-search/Chart.yaml
- charts/hocs-search/templates/_envs.tpl
Updates:
- Add consumer to the search-consumer chart.
- Now use the values file for each deployment to specify if the AWS_SQS_ENABLED env is set.
> Change search queue consuming behaviour

- charts/generic-service/Chart.yaml
- charts/generic-service/templates/deployment.yaml
This was present in the non-helm deployment
> 🐛 HOCS-6000: Add 'https://' to the keycloak cookie domain.

- charts/hocs-queue-tool/Chart.yaml
- charts/hocs-queue-tool/templates/_envs.tpl
- charts/hocs-queue-tool/values.yaml
Pass through the environmental queue settings as a comma seperated values into the spring profile environment variable.
> HOCS-5996: use queue settings for spring profiles

- charts/hocs-search-consumer-opensearch/Chart.yaml
- charts/hocs-search-consumer-opensearch/templates/_envs.tpl
- charts/hocs-search-consumer-opensearch/values.yaml
- charts/hocs-search-opensearch/Chart.yaml
- charts/hocs-search-opensearch/templates/_envs.tpl
- charts/hocs-search-opensearch/values.yaml
Add the base charts at version 1.0.0 for both the OpenSearch consumer and API.
> HOCS-5984: add base OpenSearch charts

- charts/hocs-audit/Chart.yaml
- charts/hocs-audit/values.yaml
- charts/hocs-extracts/Chart.yaml
- charts/hocs-extracts/templates/refreshDcuAggregatedCasesView.yaml
- charts/hocs-extracts/values.yaml
Audit no longer has the API endpoints enabled due to a profile restriction, this change moves the CronJob to extracts as that has the endpoints enabled.
As its expected that extracts is going to have a read only replica, this will shortly be moved out of an API call and into a DB cronjob.
> HOCS-6004: move mat-view cronjob to extract chart

- charts/hocs-audit/Chart.yaml
- charts/hocs-audit/templates/_envs.tpl
- charts/hocs-audit/templates/hocs-refresh-dcu-cases-view-job-networkpolicy.yaml
- charts/hocs-audit/templates/refresh-dcu-cases-view-job.yaml
- charts/hocs-audit/values.yaml
- charts/hocs-extracts/Chart.yaml
- charts/hocs-extracts/values.yaml
As the materialised view cannot fully be run from the extracts
deployment, this has been moved to the audit service again.
As the audit service does not serve long-running commands from the
users and only needs to support the materialised job refresh. This can
have the timeout deactivated on the service - this overwrites the
default 60 seconds on the service.
> HOCS-6146:  move materialised view from extracts to audit

- charts/hocs-case-creator/Chart.yaml
- charts/hocs-case-creator/templates/_envs.tpl
- charts/hocs-case-creator/values.yaml
- charts/hocs-case-migrator/Chart.yaml
- charts/hocs-case-migrator/templates/_envs.tpl
- charts/hocs-case-migrator/values.yaml
Change to case creator deployments to use a boolean property for ignoring the messages. This by default is set to false but should be overridden within respective environments.
> HOCS-6243: change ignore message property

- charts/hocs-case-creator/Chart.yaml
- charts/hocs-case-creator/templates/_envs.tpl
- charts/hocs-case-migrator/Chart.yaml
- charts/hocs-case-migrator/templates/_envs.tpl
Add the corresponding environment database variables that should be used for connection to the database for both case-creator and the case-migrator.
> HOCS-6168: add database environment variables

- charts/hocs-case-creator/Chart.yaml
- charts/hocs-case-creator/values.yaml
- charts/hocs-case-migrator/Chart.yaml
- charts/hocs-case-migrator/values.yaml
As the case creator services need access to the RDS now, this change adds the missing label that allows this communication with the environment network policies.
> HOCS-6168: add missing pod label

- .github/workflows/release-charts.yml
This change allows for the manual triggering of the release charts workflow job for when patches need to be applied to previous major/minor versions.
> Allow manual release charts trigger

- charts/hocs-case-creator/Chart.yaml
- charts/hocs-case-creator/templates/process-messages-job.yml
- charts/hocs-case-creator/values.yaml
Add processing cronjob to the deployment for case creator. This is set to not deploy by default, to ensure that environments don't try to use this prematurely. This job sends a POST request through to case-creator via its newly added service to process up to `maxMessages` amount of messages.
> HOCS-6249: add processing cron job

- charts/hocs-case-creator/Chart.yaml
- charts/hocs-case-creator/templates/hocs-case-creator-process-messages-job-networkpolicy.yaml
- charts/hocs-case-creator/templates/hocs-case-creator-process-messages-job.yml
Kubernetes does not support multi-line with args blocks, this change fixes the process-messages-job.yml to correctly run the curl command.
> Fix process messages cronjob

- charts/hocs-case-creator/Chart.yaml
- charts/hocs-case-creator/templates/hocs-case-creator-process-messages-job.yml
The current solution fails the cronjob on every run invocation. This change fixes a number of issues with the argument passed:
- Remove spaces around variable assignation, the space after the equals attempts to run a method called http_status that does not exist. Removing the spaces treats this as variable assignation.
- Add `%{http_code}` watch return that tells curl to write out the status code.
- Remove double square brackets as our base image does not alias bash to shell.
> HOCS-6418: correctly handle curl response

- charts/hocs-txa-document-extractor/Chart.yaml
- charts/hocs-txa-document-extractor/templates/cs-txa-deletes-job.yml
- charts/hocs-txa-document-extractor/templates/cs-txa-ingests-job.yml
- charts/hocs-txa-document-extractor/templates/wcs-txa-deletes-job.yml
- charts/hocs-txa-document-extractor/templates/wcs-txa-ingests-job.yml
- charts/hocs-txa-document-extractor/values.yaml
Add helm charts for hocs-txa-document-extractor cronjobs. 1 cronjob for each of:
- ingests from CS to TXA
- ingests from WCS to TXA
- deletes from CS to TXA
- deletes from WCS to TXA
> Hocs txa document extractor

- charts/hocs-txa-document-extractor/Chart.yaml
- charts/hocs-txa-document-extractor/templates/cs-txa-deletes-job.yml
- charts/hocs-txa-document-extractor/templates/cs-txa-ingests-job.yml
- charts/hocs-txa-document-extractor/templates/wcs-txa-deletes-job.yml
- charts/hocs-txa-document-extractor/templates/wcs-txa-ingests-job.yml
- charts/hocs-txa-document-extractor/values.yaml
Fix the chart for hocs-txa-document-extractor by renaming Chart template values to remove the invalid character (Helm does not like hyphens in the names).
> Remove invalid character from hocs-txa-document-extractor Chart

- charts/hocs-txa-document-extractor/Chart.yaml
- charts/hocs-txa-document-extractor/templates/cs-txa-deletes-job.yml
- charts/hocs-txa-document-extractor/templates/cs-txa-ingests-job.yml
- charts/hocs-txa-document-extractor/templates/wcs-txa-deletes-job.yml
- charts/hocs-txa-document-extractor/templates/wcs-txa-ingests-job.yml
Use distinct secrets for cs & wcs jobs.
In dev, all jobs used the same secret object 'txa-secrets' because the database user had the same credentials in the CS RDS as it did in the WCS RDS. This is not the case in preprod or prod - the credentials are different.
I have updated the secrets in the cs-txa-notprod namespace to convert the 1 txa-secrets secret to 2 distinct secrets (cs-txa-secrets and wcs-txa-secrets). The secrets are the cs-txa-preprod and cs-txa-prod namespaces are already split into cs-txa-secrets and wcs-txa-secrets.
This pull request is to update the helm Chart for hocs-txa-document-extractor so that the cs/wcs jobs target the correct secret in preprod & prod.
> Update hocs-txa-document-extractor chart to v1.0.3
